import { Inter } from "next/font/google";
import ServerUserProvider from "@/components/UserProvider";
import GlobalStyles from "./global.styled";
import StyledComponentsRegistry from "@/components/StyledComponentsRegistry";
import ServerThemedRoot from "@/components/ThemedRoot/ServerThemedRoot";
import { StBody, StMain } from "./app.styled";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StyledComponentsRegistry>
      <ServerThemedRoot>
          <ServerUserProvider>
            <StBody className={inter.className}>
              <Header />
              <StMain>
                {children}
              </StMain>
              <GlobalStyles />
            </StBody>
          </ServerUserProvider>
      </ServerThemedRoot>
    </StyledComponentsRegistry>
  );
}
