import { Inter } from "next/font/google";
import ServerUserProvider from "@/components/UserProvider";
import GlobalStyles from "./global.styled";
import StyledComponentsRegistry from "@/components/StyledComponentsRegistry";
import ServerThemedRoot from "@/components/ThemedRoot/ServerThemedRoot";
import { StBody, StMain } from "./app.styled";
import Header from "@/components/Header";
import SocketContextProvider from "@/components/SocketContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StyledComponentsRegistry>
      <ServerThemedRoot>
        <ServerUserProvider>
          <SocketContextProvider>
            <StBody className={inter.className}>
              <Header />
              <StMain>{children}</StMain>
              <GlobalStyles />
            </StBody>
          </SocketContextProvider>
        </ServerUserProvider>
      </ServerThemedRoot>
    </StyledComponentsRegistry>
  );
}
