import { Inter } from "next/font/google";
import ServerUserProvider from "@/components/UserProvider";
import GlobalStyles from "./global.styled";
import StyledComponentsRegistry from "@/components/StyledComponentsRegistry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StyledComponentsRegistry>
      <html lang="en">
        <body className={inter.className}>
          <ServerUserProvider>{children}</ServerUserProvider>
          <GlobalStyles />
        </body>
      </html>
    </StyledComponentsRegistry>
  );
}
